name: Flutter APK Build

on:
  push:
    branches:
      - main  # or any other branch you'd like to trigger the action on

  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable  # Set the Flutter channel to stable
        flutter-version-file: pubspec.yaml  # Specify pubspec.yaml to determine version

    - name: Check Flutter version
      run: flutter --version  # Verifies the Flutter version in the workflow

    - name: Install Flutter dependencies
      run: flutter pub get  # Install project dependencies

    - name: Build APK
      run: flutter build apk --release  # Build the APK in release mode

    - name: Upload APK to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk  # Path to the generated APK file
